os: linux
sudo: required
dist: trusty
language: php

php:
    - 7.4
    # - 7.3
    # - 7.2
    # - 7.1
    - 7.0

env:
    - NODE_RELEASE=

jobs:
    fast_finish: true
    include:
        - php: 7.3
          env: NODE_RELEASE=17.x
        - php: 7.2
          env: NODE_RELEASE=16.x
        - php: 7.1
          env: NODE_RELEASE=15.x
    allow_failures:
        - php: '7.0'

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.npm
        - node_modules
    timeout: 1440

before_script:
    - make install_node

install:
    - composer install
    - make npm_install

script:
    - make test_php
    - make test_php_cli
    - make test_js_cli
    - make coverage_js

after_script:
    - make codecov
